// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: StopTimeOpt/StopTimeOpt.proto

package StopTimeOpt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopTimeOptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinTime int32 `protobuf:"varint,1,opt,name=min_time,json=minTime,proto3" json:"min_time,omitempty"`
	MaxTime int32 `protobuf:"varint,2,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
}

func (x *StopTimeOptRequest) Reset() {
	*x = StopTimeOptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StopTimeOpt_StopTimeOpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopTimeOptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTimeOptRequest) ProtoMessage() {}

func (x *StopTimeOptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StopTimeOpt_StopTimeOpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTimeOptRequest.ProtoReflect.Descriptor instead.
func (*StopTimeOptRequest) Descriptor() ([]byte, []int) {
	return file_StopTimeOpt_StopTimeOpt_proto_rawDescGZIP(), []int{0}
}

func (x *StopTimeOptRequest) GetMinTime() int32 {
	if x != nil {
		return x.MinTime
	}
	return 0
}

func (x *StopTimeOptRequest) GetMaxTime() int32 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

type StopTimeOptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode int32 `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	StopTime   int32 `protobuf:"varint,2,opt,name=stop_time,json=stopTime,proto3" json:"stop_time,omitempty"`
}

func (x *StopTimeOptResponse) Reset() {
	*x = StopTimeOptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StopTimeOpt_StopTimeOpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopTimeOptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTimeOptResponse) ProtoMessage() {}

func (x *StopTimeOptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StopTimeOpt_StopTimeOpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTimeOptResponse.ProtoReflect.Descriptor instead.
func (*StopTimeOptResponse) Descriptor() ([]byte, []int) {
	return file_StopTimeOpt_StopTimeOpt_proto_rawDescGZIP(), []int{1}
}

func (x *StopTimeOptResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *StopTimeOptResponse) GetStopTime() int32 {
	if x != nil {
		return x.StopTime
	}
	return 0
}

var File_StopTimeOpt_StopTimeOpt_proto protoreflect.FileDescriptor

var file_StopTimeOpt_StopTimeOpt_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x2f, 0x53, 0x74,
	0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x22, 0x4a, 0x0a, 0x12,
	0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6d, 0x61, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70,
	0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x5e, 0x0a,
	0x08, 0x4d, 0x65, 0x74, 0x72, 0x6f, 0x4f, 0x70, 0x74, 0x12, 0x52, 0x0a, 0x0b, 0x53, 0x74, 0x6f,
	0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x12, 0x1f, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x54,
	0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65,
	0x4f, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a,
	0x18, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x53, 0x74,
	0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_StopTimeOpt_StopTimeOpt_proto_rawDescOnce sync.Once
	file_StopTimeOpt_StopTimeOpt_proto_rawDescData = file_StopTimeOpt_StopTimeOpt_proto_rawDesc
)

func file_StopTimeOpt_StopTimeOpt_proto_rawDescGZIP() []byte {
	file_StopTimeOpt_StopTimeOpt_proto_rawDescOnce.Do(func() {
		file_StopTimeOpt_StopTimeOpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_StopTimeOpt_StopTimeOpt_proto_rawDescData)
	})
	return file_StopTimeOpt_StopTimeOpt_proto_rawDescData
}

var file_StopTimeOpt_StopTimeOpt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_StopTimeOpt_StopTimeOpt_proto_goTypes = []interface{}{
	(*StopTimeOptRequest)(nil),  // 0: StopTimeOpt.StopTimeOptRequest
	(*StopTimeOptResponse)(nil), // 1: StopTimeOpt.StopTimeOptResponse
}
var file_StopTimeOpt_StopTimeOpt_proto_depIdxs = []int32{
	0, // 0: StopTimeOpt.MetroOpt.StopTimeOpt:input_type -> StopTimeOpt.StopTimeOptRequest
	1, // 1: StopTimeOpt.MetroOpt.StopTimeOpt:output_type -> StopTimeOpt.StopTimeOptResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_StopTimeOpt_StopTimeOpt_proto_init() }
func file_StopTimeOpt_StopTimeOpt_proto_init() {
	if File_StopTimeOpt_StopTimeOpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_StopTimeOpt_StopTimeOpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopTimeOptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StopTimeOpt_StopTimeOpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopTimeOptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StopTimeOpt_StopTimeOpt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_StopTimeOpt_StopTimeOpt_proto_goTypes,
		DependencyIndexes: file_StopTimeOpt_StopTimeOpt_proto_depIdxs,
		MessageInfos:      file_StopTimeOpt_StopTimeOpt_proto_msgTypes,
	}.Build()
	File_StopTimeOpt_StopTimeOpt_proto = out.File
	file_StopTimeOpt_StopTimeOpt_proto_rawDesc = nil
	file_StopTimeOpt_StopTimeOpt_proto_goTypes = nil
	file_StopTimeOpt_StopTimeOpt_proto_depIdxs = nil
}
